# this file is in a random dir to ensure the path of context values files doesn't matter
# It is named different from it's context name to test that too

context:
  name: context-dev-test
  # keys skipped so default values are used
  active: true
  type: development # custom key
  environment: dev
  env: dev
  custom_unicode: "测试"

  component:
    - name: prometheus-name-test
      config:
        active: true
        for_commit: false
        path: common-templates/prometheus
        priority: 1
        required: false
      vars:
        helm_chart_version: 0.9.1
        crd_chart_version: 0.1.0
    - name: test-service-unicode
      type: ClusterIP
      port: 80
      config:
        priority: 20
        active: true
        required: false
        for_commit: false
      vars:
        component_name: unicode_mixed
        description: "This is a test component with 中文 content"
